version: "2"
services:
  angola-ui:
    image: openlmis/dev-ui:9.0.7-SNAPSHOT
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - "9000:9000"
      - "9876:9876"
    env_file: .env
    volumes_from:
      - auth-ui
      - fulfillment-ui
      - referencedata-ui
      - requisition-ui
      - report-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
      - offline-ui
    depends_on:
      - auth-ui
      - fulfillment-ui
      - referencedata-ui
      - requisition-ui
      - report-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
      - offline-ui
  auth-ui:
    image: openlmis/auth-ui:6.2.11
    volumes:
      - '/openlmis-auth-ui'
  fulfillment-ui:
    image: openlmis/fulfillment-ui:6.1.4
    volumes:
      - '/openlmis-fulfillment-ui'
  referencedata-ui:
    image: openlmis/referencedata-ui:5.6.11
    volumes:
      - '/openlmis-referencedata-ui'
  report-ui:
    image: openlmis/report-ui:5.2.11
    volumes:
      - '/openlmis-report-ui'
  requisition-ui:
    image: openlmis/requisition-ui:7.0.11
    volumes:
      - '/openlmis-requisition-ui'
  stockmanagement-ui:
    image: openlmis/stockmanagement-ui:2.1.6
    volumes:
     - '/openlmis-stockmanagement-ui'
  ui-components:
    image: openlmis/ui-components:7.2.10
    volumes:
      - '/openlmis-ui-components'
  ui-layout:
    image: openlmis/ui-layout:5.2.5
    volumes:
      - '/openlmis-ui-layout'
  offline-ui:
    image: openlmis/offline-ui:1.0.5
    volumes:
      - '/openlmis-offline-ui'
  image:
    build: .
    image: openlmisao/angola-ui:latest